import type { Tx } from "./ledger";
import type { Account, Recurring } from "./models";

function at(stamp: string): number {
  return new Date(stamp.replace(" ", "T") + "+08:00").getTime();
}

function row(
  partial: Omit<Tx, "id" | "status" | "orderId" | "note" | "rawCategory" | "origin" | "title"> & {
    title?: string;
    id: string;
  },
): Tx {
  return {
    title: partial.title ?? "",
    status: "交易成功",
    orderId: partial.id,
    note: "",
    rawCategory: "",
    origin: "sample",
    book: "main",
    ledgerId: "default",
    ...partial,
  };
}

export const SAMPLE_TX: Tx[] = [
  row({
    id: "s-rent",
    time: at("2026-08-01 09:12:00"),
    amountFen: 280000,
    direction: "expense",
    category: "housing",
    merchant: "房东·陈",
    title: "八月房租",
    source: "alipay",
    method: "余额宝",
  }),
  row({
    id: "s-power",
    time: at("2026-08-01 10:04:11"),
    amountFen: 12840,
    direction: "expense",
    category: "housing",
    merchant: "国网江苏电力",
    title: "电费",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-luckin1",
    time: at("2026-08-02 08:21:44"),
    amountFen: 1590,
    direction: "expense",
    category: "food",
    merchant: "瑞幸咖啡",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-metro1",
    time: at("2026-08-02 08:44:02"),
    amountFen: 600,
    direction: "expense",
    category: "transport",
    merchant: "南京地铁",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-hema",
    time: at("2026-08-03 19:12:33"),
    amountFen: 8620,
    direction: "expense",
    category: "food",
    merchant: "盒马鲜生",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-mobile",
    time: at("2026-08-03 20:01:09"),
    amountFen: 9900,
    direction: "expense",
    category: "telecom",
    merchant: "中国移动",
    title: "话费充值",
    source: "alipay",
    method: "余额宝",
  }),
  row({
    id: "s-taobao",
    time: at("2026-08-04 21:18:00"),
    amountFen: 5900,
    direction: "expense",
    category: "shopping",
    merchant: "淘宝",
    title: "日用收纳",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-meituan1",
    time: at("2026-08-05 12:18:03"),
    amountFen: 3280,
    direction: "expense",
    category: "food",
    merchant: "美团",
    title: "黄焖鸡米饭",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-didi",
    time: at("2026-08-06 22:41:15"),
    amountFen: 2450,
    direction: "expense",
    category: "transport",
    merchant: "滴滴出行",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-salary",
    time: at("2026-08-07 09:02:00"),
    amountFen: 1280000,
    direction: "income",
    category: "income",
    merchant: "公司发薪",
    title: "八月工资",
    source: "alipay",
    method: "余额",
  }),
  row({
    id: "s-starbucks",
    time: at("2026-08-08 14:11:22"),
    amountFen: 3800,
    direction: "expense",
    category: "food",
    merchant: "星巴克",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-music",
    time: at("2026-08-08 20:00:01"),
    amountFen: 1500,
    direction: "expense",
    category: "fun",
    merchant: "网易云音乐",
    title: "黑胶 VIP",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-jd",
    time: at("2026-08-09 11:26:40"),
    amountFen: 29900,
    direction: "expense",
    category: "digital",
    merchant: "京东",
    title: "键盘",
    source: "alipay",
    method: "花呗分期",
  }),
  row({
    id: "s-mom",
    time: at("2026-08-10 18:03:12"),
    amountFen: 50000,
    direction: "expense",
    category: "gift",
    merchant: "转账给妈妈",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-yonghui",
    time: at("2026-08-11 19:44:08"),
    amountFen: 6430,
    direction: "expense",
    category: "daily",
    merchant: "永辉超市",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-eleme",
    time: at("2026-08-12 12:51:00"),
    amountFen: 4100,
    direction: "expense",
    category: "food",
    merchant: "饿了么",
    title: "午餐",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-gas",
    time: at("2026-08-13 17:22:19"),
    amountFen: 28000,
    direction: "expense",
    category: "transport",
    merchant: "中石化",
    title: "加油",
    source: "alipay",
    method: "余额宝",
  }),
  row({
    id: "s-movie",
    time: at("2026-08-14 20:05:33"),
    amountFen: 8800,
    direction: "expense",
    category: "fun",
    merchant: "淘票票",
    title: "电影票",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-pharmacy",
    time: at("2026-08-15 10:16:47"),
    amountFen: 3650,
    direction: "expense",
    category: "health",
    merchant: "大参林药店",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-kfc",
    time: at("2026-08-16 18:28:01"),
    amountFen: 4700,
    direction: "expense",
    category: "food",
    merchant: "肯德基",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-pdd",
    time: at("2026-08-17 21:09:55"),
    amountFen: 2990,
    direction: "expense",
    category: "shopping",
    merchant: "拼多多",
    title: "收纳盒",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-rail",
    time: at("2026-08-18 07:12:00"),
    amountFen: 15600,
    direction: "expense",
    category: "travel",
    merchant: "铁路12306",
    title: "南京南-上海虹桥",
    source: "alipay",
    method: "余额宝",
  }),
  row({
    id: "s-family",
    time: at("2026-08-19 22:11:04"),
    amountFen: 1850,
    direction: "expense",
    category: "daily",
    merchant: "全家",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-meituan2",
    time: at("2026-08-20 12:40:18"),
    amountFen: 2700,
    direction: "expense",
    category: "food",
    merchant: "美团",
    title: "麻辣烫",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-redpack",
    time: at("2026-08-21 19:00:22"),
    amountFen: 8800,
    direction: "expense",
    category: "gift",
    merchant: "微信红包",
    title: "同事生日",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-cut",
    time: at("2026-08-22 15:33:40"),
    amountFen: 8000,
    direction: "expense",
    category: "daily",
    merchant: "隔壁理发",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-luckin2",
    time: at("2026-08-23 08:02:11"),
    amountFen: 1590,
    direction: "expense",
    category: "food",
    merchant: "瑞幸咖啡",
    source: "wechat",
    method: "零钱",
  }),
  row({
    id: "s-noodle",
    time: at("2026-08-24 12:18:03"),
    amountFen: 3280,
    direction: "expense",
    category: "food",
    merchant: "美团",
    title: "担担面",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-coffee",
    time: at("2026-08-25 09:14:27"),
    amountFen: 2200,
    direction: "expense",
    category: "food",
    merchant: "Seesaw Coffee",
    source: "alipay",
    method: "花呗",
  }),
  row({
    id: "s-jul-rent",
    time: at("2026-07-01 09:10:00"),
    amountFen: 280000,
    direction: "expense",
    category: "housing",
    merchant: "房东·陈",
    title: "七月房租",
    source: "alipay",
    method: "余额宝",
  }),
  row({
    id: "s-jul-salary",
    time: at("2026-07-07 09:02:00"),
    amountFen: 1280000,
    direction: "income",
    category: "income",
    merchant: "公司发薪",
    title: "七月工资",
    source: "alipay",
    method: "余额",
  }),
  row({
    id: "s-jul-food",
    time: at("2026-07-18 12:22:00"),
    amountFen: 4680,
    direction: "expense",
    category: "food",
    merchant: "美团",
    title: "牛肉面",
    source: "alipay",
    method: "花呗",
  }),
];

export const SAMPLE_RECURRING: Recurring[] = [
  {
    id: "r-rent",
    title: "房租",
    amountFen: 280000,
    category: "housing",
    cadence: "monthly",
    nextDue: "2026-09-01",
    remindDays: 5,
    note: "房东·陈",
    active: true,
  },
  {
    id: "r-card",
    title: "花呗还款",
    amountFen: 210000,
    category: "housing",
    cadence: "monthly",
    nextDue: "2026-09-09",
    remindDays: 3,
    note: "",
    active: true,
  },
  {
    id: "r-icloud",
    title: "iCloud+",
    amountFen: 600,
    category: "digital",
    cadence: "monthly",
    nextDue: "2026-08-28",
    remindDays: 2,
    note: "订阅",
    active: true,
  },
];

export const SAMPLE_ACCOUNTS: Account[] = [
  { id: "a-yuebao", kind: "deposit", name: "余额宝", balanceFen: 1280000, note: "", counterparty: "" },
  { id: "a-bank", kind: "deposit", name: "招商储蓄", balanceFen: 5200000, note: "", counterparty: "" },
  { id: "a-fund", kind: "investment", name: "指数基金", balanceFen: 860000, note: "", counterparty: "" },
  { id: "a-huabei", kind: "credit", name: "花呗", balanceFen: 210000, note: "下月9日还", counterparty: "支付宝" },
  { id: "a-friend", kind: "loan", name: "欠小林", balanceFen: 150000, note: "", counterparty: "小林" },
  { id: "a-lend", kind: "receivable", name: "同学借款", balanceFen: 80000, note: "", counterparty: "阿宁" },
];
