import { chromium } from "playwright";
const browser = await chromium.launch({ headless: true, args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message));
await page.goto("http://127.0.0.1:8080/", { waitUntil: "domcontentloaded", timeout: 15000 });
await page.getByText("月梨").first().waitFor({ timeout: 10000 });
await page.getByRole("button", { name: "导入", exact: true }).click();
const chooserPromise = page.waitForEvent("filechooser");
await page.getByRole("button", { name: /选择 CSV/ }).click();
const chooser = await chooserPromise;
await chooser.setFiles("/tmp/alipay-demo.csv");
await page.getByText("待入册").waitFor({ timeout: 8000 });
console.log("PREVIEW", (await page.locator("body").innerText()).includes("支付宝账本"));
await page.getByRole("button", { name: /确认入册|记入/ }).click().catch(async () => {
  await page.getByRole("button", { name: /入册/ }).last().click();
});
await page.waitForTimeout(800);
const home = await page.locator("body").innerText();
console.log("BOOK_ALIPAY", home.includes("支付宝"));
console.log("COFFEE", home.includes("咖啡"));
console.log("TAKEOUT", home.includes("外卖"));
console.log("GROCERY", home.includes("买菜"));
console.log("TAXI", home.includes("打车"));
console.log("SALARY", home.includes("工资") || home.includes("收入"));
await page.screenshot({ path: "/workspace/screenshots/qa-alipay-book.png" });
await page.getByRole("button", { name: /^月梨/ }).click();
await page.waitForTimeout(300);
console.log("BACK_MAIN", (await page.locator("body").innerText()).includes("本月支出"));
await browser.close();
